### PR TITLE
Resolve packaging unit broken styles

### PR DESCRIPTION
**Pull request by makombe**
## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.

## Screenshots

Screenshot from 2024-01-29 23-19-02

### CODE REVIEW

**Comment by makombe** [comment]
@patryllus You can have a look. Thanks

**Review by jabahum — COMMENTED** [review]
Thanks @makombe i wanted to ask in the video below is this behaviour normal

https://github.com/METS-Programme/esm-ugandaemr-stock-management/assets/24471994/5b58c7a2-f717-444d-bd06-d2eddc27abef

**Comment by makombe** [comment]
@jabahum I think that is not normal and will require a fix. Here I was just addressing styling issues. Thanks

**Comment by jabahum** [comment]
> @jabahum I think that is not normal and will require a fix. Here I was just addressing styling issues. Thanks for the catch.

alright @makombe thanks

**Pull request merged**
