### PR TITLE
U4X-264 : Add bulk items import 

### PR DESCRIPTION
**Pull request by jabahum**
## Requirements
- [ ] This PR has a title that briefly describes the work done including a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) type prefix and a Jira ticket number if applicable. See existing PR titles for inspiration.

#### For changes to apps
- [ ]  My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide) and [**design documentation**](https://zeroheight.com/23a080e38/p/880723-introduction).

#### If applicable
- [ ] My work includes tests or is validated by existing tests.

## Related Issue

https://metsprogramme.atlassian.net/browse/U4X-264

### CODE REVIEW

**Comment by makombe** [comment]
@slubwama Are you at a position to help review this, We would like to test the import feature with a template sample we have already populated. Thanks

**Comment by jabahum** [comment]
> @slubwama, @akileng56 Are you at a position to help review this, Our QA would like to test the import feature with a template sample we have already populated. Thanks

@makombe there is an issue on the backend side holding this PR @slubwama is working on this

**Comment by ojwanganto** [comment]
@slubwama  @jabahum any updates on this?

**Comment by jabahum** [comment]
@Mwanje is looking into this PR to test

**Comment by ojwanganto** [comment]
Thanks for the feedback

**Comment by Mwanje** [comment]
@slubwama the current import file structure needs to be reorganised to accommodate numeric fields.

**Comment by makombe** [comment]
@jabahum, @Mwanje @slubwama  what do you think, can we merge this in then we can move it forward from there? The fixes can be done in follow up PR

**Pull request merged**
